spring:
  application:
    name: tasks

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/flexisaf
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
